service: fastfood-product-service

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-existing-cloudfront-lambda-edge

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId: d0ewo299u4
    restApiRootResourceId: cbegvswvsj
  timeout: 60
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  main:
    handler: dist/src/lambda.handler
    timeout: 60
    events:
      - http:
          method: ANY
          cors: true
          path: "fprs/{proxy+}"

resources:
  Resources:
    ApiGatewayRestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Name: ExistingApiGateway
        EndpointConfiguration:
          Types:
            - REGIONAL
      DeletionPolicy: Retain

custom:
  existingApiGateway:
    restApiId: d0ewo299u4
    restApiRootResourceId: cbegvswvsj
