service: serverless-example

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
functions:
  main:
    handler: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          cors: true
          path: /
      - http:
          method: ANY
          cors: true
          path: "{proxy+}"
package:
  individually: true
  exclude:
    - .vscode
    - .git
    - thunder-tests
    - undefined
    - config
    - tmp/**
